#!/bin/bash
read -p "enter folder name: " folder;

FILES=/Users/andrewakhlaghi/Desktop/test_dir/$folder/*
for f in $FILES;
do
  tiff=${f%.*}.tiff
  convert -density 300 $f -depth 8 -strip -background white -alpha off $tiff
  ocr=${f%.*}_ocr
  tlate=${f%.*}_trans
  tesseract $tiff $ocr -l rus
  trans -e bing :eng file://$ocr.txt > $tlate.txt
  sleep 1m
done

#need to install ImageMagick, Tesseract, and Translate Shell (formerly Google Translate CLI) 
#this will only translate one page at a time, which is necessary for the translation to work properly
#Google translate and other online translators cap your access and will block your IP 
